### ISSUE TITLE
Assets are not populating.

### ISSUE THREAD

**Issue by BloodBlight** [netbootxyz/netboot.xyz#1042]
**Describe the bug**
Both tracked and un-tracked assets are blank after pulling files.

**To Reproduce**
1. Deployed docker using:
```
version: '3.7'

volumes:
  NetBoot-config: 
    external: true
  NetBoot-assets: 
    external: true

services:
  NetBoot:
    container_name: NetBoot
    image: linuxserver/netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - NetBoot-config:/config
      - NetBoot-assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8090:80 #optional
    restart: always
```
2. Browsed to port 3000
3. Downloaded assets
4. Files are there, but list is empty.
5. Restarted docker, lists is still empty.

**Expected behavior**
Downloaded assets should be in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/3953102/138362108-f3f096c2-f7d0-498a-b3ba-db2da272546c.png)

**Additional context**
First time using netboot.xyz.

|Component|Version|
|----|----|
|Webapp Version: | 0.6.5|
|Menus Version: | 2.0.51|
|TFTP: | tftp-hpa 5.2, with remap, without tcpwrappers|
|WebServer: | nginx version: nginx/1.18.0|
|Remote Assets at:| 2.0.51|
