### ISSUE TITLE
[BUG] win_base_url not listed when booting to netbootxyz windows menu

### ISSUE THREAD

**Issue by deffcolony** [netbootxyz/netboot.xyz#1344]
# Describe the bug
When i tried to set the base url for **win_base_url** at **boot.cfg** it does not get displayed in the boot menu for windows... i have to type the url manually everytime i boot to netbootxyz menu

# Environment
Docker on a ubuntu server

# To Reproduce
1. Visit your netbootxyz dashboard
2. Go to Menus > boot.cfg
3. Add or replace the following line set win_base_url http://YOUR_NETBOOTXYZ_IP:/winpe
4. Do a networkboot and go to Distributions: > Windows

I use the following docker-compose.yml maybe this could help?

```yaml
version: "3.8"

services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
#      MENU_VERSION: 1.9.9 #optional unset is latest version
      PORT_RANGE: 30000:30010 #optional
      SUBFOLDER: / #optional
    volumes:
      - ./config:/config
      - ./assets:/assets
    ports:
      - 9170:3000
      - 9171:69/udp
      - 9172:80 #optional
    restart: unless-stopped

  samba:
    image: servercontainers/samba:latest
#    image: ghcr.io/servercontainers/samba
    container_name: netbootxyz-samba
    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: netbootsamba
      SAMBA_CONF_LOG_LEVEL: 3
      # uncomment to disable optional services
#      WSDD2_DISABLE: 1
#      AVAHI_DISABLE: 1
      GROUP_family: 1500
      ACCOUNT_netboot: yourpasswordhere
      UID_netboot: 1000
      GROUPS_netboot: family
      SAMBA_VOLUME_CONFIG_netbootonly: "[netboot]; path=/shares/netboot; valid users = netboot; guest ok = no; read only = no; browseable = yes"
      SAMBA_VOLUME_CONFIG_shared_home: "[Home]; path=/shares/homes/%U; valid users = netboot, guest ok = no; read only = no; browseable = yes"
      SAMBA_VOLUME_CONFIG_public: "[Public]; path=/shares/public; valid users = netboot, guest ok = no; read only = no; browseable = yes; force group = family"
      SAMBA_VOLUME_CONFIG_public_ro: "[Public ReadOnly]; path=/shares/public; guest ok = yes; read only = yes; browseable = yes; force group = family"
      SAMBA_VOLUME_CONFIG_timemachine: "[TimeMachine]; path=/shares/timemachine/%U; valid users = netboot, guest ok = no; read only = no; browseable = yes; fruit:time machine = yes; fruit:time machine max size = 500G"
    volumes:
      - /etc/avahi/services/:/external/avahi
      - ./samba/shares/netboot:/shares/netboot
      - ./samba/shares/public:/shares/public
      - ./samba/shares/homes:/shares/homes
      - ./samba/shares/timemachine:/shares/timemachine
    restart: unless-stopped
```

# Expected behavior
The base url should be listed in the netbootxyz menu options for windows

# Screenshots

I have set the correct base url for winpe
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/fdb39c22-6170-4d72-ba9c-86ffb3069496)

The base url does indeed get saved in the file mounted from the docker volume when i save it from the dashboard page
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/82ca0a4e-8136-45fb-9d98-0665d586e057)

The base url does also get saved in the internal container files:
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/4a7b5d0b-3b94-4f01-8092-dbf354696e60)

The base url wont get displayed on a physical device meaning i have to type the url manually...
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/f972889c-df0f-467d-9188-0a33189c6761)

The base url also wont get displayed on a virtual machine meaning i have to type the url manually...
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/c8991990-e1b4-451b-a795-e5efec2d2c8b)

**Additional context**
